services:
  postgis:
    image: postgis/postgis:17-3.5
    container_name: pladi-postgis
    env_file: ../.env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
      - ../../sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
